//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameGenApp.ServiceReferenceIIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceIIS.IPackageServices")]
    public interface IPackageServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/DoWork", ReplyAction="http://tempuri.org/IPackageServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/DoWork", ReplyAction="http://tempuri.org/IPackageServices/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/GetPackage", ReplyAction="http://tempuri.org/IPackageServices/GetPackageResponse")]
        PostProjectWebServices.Models.Package GetPackage(int packageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/GetPackage", ReplyAction="http://tempuri.org/IPackageServices/GetPackageResponse")]
        System.Threading.Tasks.Task<PostProjectWebServices.Models.Package> GetPackageAsync(int packageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CreatePackage", ReplyAction="http://tempuri.org/IPackageServices/CreatePackageResponse")]
        void CreatePackage(string firstName, string lastName, string street, string city, string postalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CreatePackage", ReplyAction="http://tempuri.org/IPackageServices/CreatePackageResponse")]
        System.Threading.Tasks.Task CreatePackageAsync(string firstName, string lastName, string street, string city, string postalCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPackageServicesChannel : NameGenApp.ServiceReferenceIIS.IPackageServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackageServicesClient : System.ServiceModel.ClientBase<NameGenApp.ServiceReferenceIIS.IPackageServices>, NameGenApp.ServiceReferenceIIS.IPackageServices {
        
        public PackageServicesClient() {
        }
        
        public PackageServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackageServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public PostProjectWebServices.Models.Package GetPackage(int packageId) {
            return base.Channel.GetPackage(packageId);
        }
        
        public System.Threading.Tasks.Task<PostProjectWebServices.Models.Package> GetPackageAsync(int packageId) {
            return base.Channel.GetPackageAsync(packageId);
        }
        
        public void CreatePackage(string firstName, string lastName, string street, string city, string postalCode) {
            base.Channel.CreatePackage(firstName, lastName, street, city, postalCode);
        }
        
        public System.Threading.Tasks.Task CreatePackageAsync(string firstName, string lastName, string street, string city, string postalCode) {
            return base.Channel.CreatePackageAsync(firstName, lastName, street, city, postalCode);
        }
    }
}
