//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostProjectClient.PackageWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://schemas.datacontract.org/2004/07/PostProjectWebServices.Models")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int packageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientStreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int packageId {
            get {
                return this.packageIdField;
            }
            set {
                if ((this.packageIdField.Equals(value) != true)) {
                    this.packageIdField = value;
                    this.RaisePropertyChanged("packageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientCity {
            get {
                return this.recipientCityField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientCityField, value) != true)) {
                    this.recipientCityField = value;
                    this.RaisePropertyChanged("recipientCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientFirstName {
            get {
                return this.recipientFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientFirstNameField, value) != true)) {
                    this.recipientFirstNameField = value;
                    this.RaisePropertyChanged("recipientFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientLastName {
            get {
                return this.recipientLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientLastNameField, value) != true)) {
                    this.recipientLastNameField = value;
                    this.RaisePropertyChanged("recipientLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientPostalCode {
            get {
                return this.recipientPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientPostalCodeField, value) != true)) {
                    this.recipientPostalCodeField = value;
                    this.RaisePropertyChanged("recipientPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientStreet {
            get {
                return this.recipientStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientStreetField, value) != true)) {
                    this.recipientStreetField = value;
                    this.RaisePropertyChanged("recipientStreet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PackageWebService.IPackageServices")]
    public interface IPackageServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/DoWork", ReplyAction="http://tempuri.org/IPackageServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/DoWork", ReplyAction="http://tempuri.org/IPackageServices/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/GetPackage", ReplyAction="http://tempuri.org/IPackageServices/GetPackageResponse")]
        PostProjectClient.PackageWebService.Package GetPackage(int packageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/GetPackage", ReplyAction="http://tempuri.org/IPackageServices/GetPackageResponse")]
        System.Threading.Tasks.Task<PostProjectClient.PackageWebService.Package> GetPackageAsync(int packageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CreatePackage", ReplyAction="http://tempuri.org/IPackageServices/CreatePackageResponse")]
        void CreatePackage(string firstName, string lastName, string street, string city, string postalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CreatePackage", ReplyAction="http://tempuri.org/IPackageServices/CreatePackageResponse")]
        System.Threading.Tasks.Task CreatePackageAsync(string firstName, string lastName, string street, string city, string postalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CountPackagesPerCity", ReplyAction="http://tempuri.org/IPackageServices/CountPackagesPerCityResponse")]
        void CountPackagesPerCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageServices/CountPackagesPerCity", ReplyAction="http://tempuri.org/IPackageServices/CountPackagesPerCityResponse")]
        System.Threading.Tasks.Task CountPackagesPerCityAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPackageServicesChannel : PostProjectClient.PackageWebService.IPackageServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackageServicesClient : System.ServiceModel.ClientBase<PostProjectClient.PackageWebService.IPackageServices>, PostProjectClient.PackageWebService.IPackageServices {
        
        public PackageServicesClient() {
        }
        
        public PackageServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackageServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public PostProjectClient.PackageWebService.Package GetPackage(int packageId) {
            return base.Channel.GetPackage(packageId);
        }
        
        public System.Threading.Tasks.Task<PostProjectClient.PackageWebService.Package> GetPackageAsync(int packageId) {
            return base.Channel.GetPackageAsync(packageId);
        }
        
        public void CreatePackage(string firstName, string lastName, string street, string city, string postalCode) {
            base.Channel.CreatePackage(firstName, lastName, street, city, postalCode);
        }
        
        public System.Threading.Tasks.Task CreatePackageAsync(string firstName, string lastName, string street, string city, string postalCode) {
            return base.Channel.CreatePackageAsync(firstName, lastName, street, city, postalCode);
        }
        
        public void CountPackagesPerCity() {
            base.Channel.CountPackagesPerCity();
        }
        
        public System.Threading.Tasks.Task CountPackagesPerCityAsync() {
            return base.Channel.CountPackagesPerCityAsync();
        }
    }
}
